module.exports={PRIVATE:`
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIL0qNNgWp8BeEsuzs6nBXvT7mGBfxz1a88yPq0f6exqsoAoGCCqGSM49
AwEHoUQDQgAEkJ7c0NtpqV0tuuaJK7RgU3Dq2veLk9oCJ2QuVd4MdO/Lkvu5SoOi
nCLpAPitaUPe95UAUcYLVammEMq3XSYVOw==
-----END EC PRIVATE KEY-----
`,PUBLIC:`
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkJ7c0NtpqV0tuuaJK7RgU3Dq2veL
k9oCJ2QuVd4MdO/Lkvu5SoOinCLpAPitaUPe95UAUcYLVammEMq3XSYVOw==
-----END PUBLIC KEY-----
`}
