version: "3.7"

services:
  app.capa.io:
    build: .
    restart: on-failure
    volumes:
      - ./server:/usr/src/app/server
    command: "/bin/sh -c 'yarn dev'"
    ports:
      - 8080:8080
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres.capa.io
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: EXf3hZXz4Kzqx5sr
      DB_DATABASE: capa
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  postgres.capa.io:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: EXf3hZXz4Kzqx5sr
      POSTGRES_DB: capa
    volumes:
      - volume.postgres.capa.io:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432" # temporary
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  volume.postgres.capa.io:

networks:
  default:
    # external: true
    name: capa.io
